strict-sigcheck = false

[YouTube]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[YouTube.patches]
"github:MorpheApp/morphe-patches" = []

[YT-Music]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "both"

[YT-Music.patches]
"github:MorpheApp/morphe-patches" = []
